import type { SoundName } from "./decide";

/**
 * Real-audio file manifest, consumed by FilePack (the app singleton's default
 * pack, with SynthPack as its per-sound fallback).
 *
 * The shipped clips are generated by `tools/make_sounds.py`; replace any file
 * under `ui/public/sounds/` to customise a sound. Vite serves everything in
 * `ui/public/` as-is (no hashing), so files are reachable at these paths.
 */
export const SOUND_MANIFEST: Record<SoundName, string> = {
  "hit":                "/sounds/hit.mp3",
  "hit-treble":         "/sounds/hit-treble.mp3",
  "hit-bull":           "/sounds/hit-bull.mp3",
  "miss":               "/sounds/miss.mp3",
  "bust":               "/sounds/bust.mp3",
  "leg-won":            "/sounds/leg-won.mp3",
  "game-won":           "/sounds/game-won.mp3",
  "one-eighty":         "/sounds/one-eighty.mp3",
  "checkout-available": "/sounds/checkout-available.mp3",
};
